### ISSUE TITLE
Empty resources should not be cached

### ISSUE THREAD

**Issue by sligocki** [apache/incubator-pagespeed-mod#1068]
Splitting this new issue off of discussion on Issue #1050:

From @jeffkaufman:

Simple test case: http://www.jefftk.com/simpler-include-css/

```
$ cat index.html 
<style>body {background: red}</style>
<link rel=stylesheet href="a.css" type="text/css"/>

$ cat a.css 
@import url(b.css) ;

$ cat b.css 
﻿body {background: green}

@media screen and (min-width: 240px) {
  body {background: blue}
}
```

To get the failure:

1) Pick a unique set of irrelevant PageSpeed query options to functionally clear the metadata cache.  So `?PageSpeedFilters=+[something_silly]`.
2) Open that URL in Chrome or FF, it should work, green screen.
3) Open that URL in the other one, it shouldn't work, red screen.

On the passing side `+debug` gives me:

```
<style>@import url(support-files/rwd-v2.css) ;</style><!--Flattening failed:
A media query is too complex in http://www.jefftk.com/simple-include-css
/support-files/rwd-v2.css AND Cannot rewrite http://cfd.enjoy-swimming.
com/image-files-layout/rwd-header.png as it is on an unauthorized domain-->
```

On the failing side:

```
<style></style><!--Flattening failed: A media query is too complex in
http://www.jefftk.com/simple-include-css/support-files/rwd-v2.css-->
```

**Comment by sligocki** [comment]
@sachinjsk is the original reporter.

**Comment by sachinjsk** [comment]
Is there a particular filter I could turn off to get around this issue?

**Comment by jeffkaufman** [comment]
@sachinjsk Turning off css import flattening should fix this: https://developers.google.com/speed/pagespeed/module/filter-flatten-css-imports

**Comment by sachinjsk** [comment]
Thanks @jeffkaufman. That didn't quite work. I still see a empty rewritten css cache file. Please note that I also had inline_css turned off.

**Comment by jeffkaufman** [comment]
Could you paste the config change you made?  When I test it here I can reliably reproduce with `flatten_css_imports` enabled and can't elicit the bug at all with it disabled.

(This isn't a case where flushing the cache matters; configuration options are used in the cache key for the metadata cache, and this is a metadata cache issue.)

**Comment by sligocki** [comment]
Looks to me like http://www.enjoy-swimming.sbi2b.sitesell.com/?ModPagespeedFilters=+debug does not have the bug and http://www.enjoy-swimming.sbi2b.sitesell.com/?ModPagespeedFilters=+debug,+flatten_css_imports does have the bug.

@sachinjsk, do you mean that the cache file is still on your hard disk? That shouldn't be a problem.

**Comment by jeffkaufman** [comment]
Hypothesis: the value of `flattening_suceeded_` isn't getting stored in the cache, so that if `a.css` imports `b.css`, the rewritten `a.css` isn't in cache, but the rewritten `a.css` is, then we use the cached `a.css` as if `flattening_suceeded_` even if it didn't.

**Comment by sachinjsk** [comment]
@sligocki: No, I meant the css cache file that mod_pagespeed generated was empty.

@jeffkaufman: I just tried this again. But now the page loads fine with flatten_css_imports disabled. I can't seem to reproduce what I was seeing yesterday. Yesterday the cache file that was getting generated for main.css was empty. Now I see @import url(rwd-v2.css); in it. (test url: http://www.enjoy-swimming.sbi2b.sitesell.com/?ModPagespeed=on)

Here are the changes I made yesterday:
    `ModPagespeedDisableFilters inline_css`
    `ModPagespeedDisableFilters flatten_css_imports`

**Comment by jeffkaufman** [comment]
@sachinjsk Thanks!  I'm still working on this here.  If you see this issue anymore now that you have `DisableFilters flatten_css_imports` please let me know, because that really shouldn't happen.  You can remove the `DisableFilters inline_css` if you like.

**Comment by sachinjsk** [comment]
I will. Thanks for looking into this.

**Comment by jeffkaufman** [comment]
This was fixed as a side-effect of 8f93d5cefcc8617afda1c2e41d292e362f849647, which made us more  cautious around empty resources.  Our css optimizer still is not correctly handling cases where flattening fails, incorrectly putting an empty resource in the cache, but we recover because we no longer treat empty resources as valid.

Closing this because users won't run into the "works on chrome but not firefox" problem anymore, but opening #1092 because there's still a bug in the css flattening.
