### ISSUE TITLE
pagespeed insights screams image optimisation even though all should be good?

### ISSUE THREAD

**Issue by Pionell** [apache/incubator-pagespeed-mod#1790]
Hello, I have a few websites where I did custom lazy loading, that fixed 80% of the images disappearing from th pagepseed insights image - optimise error listing. However everything thats above fold and slightly below it is still "unoptimised" even though I'm using most of the image optimisation rules for pagespeed mod:

```
 ModPagespeedEnableFilters extend_cache

 ModPagespeedImageRecompressionQuality 50

 ModPagespeedEnableFilters inline_images

 ModPagespeedEnableFilters recompress_images

 ModPagespeedEnableFilters jpeg_subsampling

 ModPagespeedEnableFilters resize_rendered_image_dimensions

 ModPagespeedEnableFilters rewrite_images

 ModPagespeedEnableFilters inline_google_font_css
```

there are a couple more rules that I'm using (js and css ones), and another issue I'm having is the inline_google_fonts_css rule does not take affect. I do use varnish cache, is this 100% it's fault?

PSI says that ~80% reduction in size is possible for ~5 images.

**Comment by Pionell** [comment]
issue is still there, the varnish cache is connected to the pagespeed mod. I see that my defer_javascript filter does not work on one of the sites, and image optimisation does not work on almost all of the sites that I tested (5+). Extend cache, combine_css do work. However i have trouble with inline google fonts filter, defer javascript, and image optimisation filters. what are the best ways to pinpoint the issue(s)?

**Comment by jmarantz** [comment]
The first step is to turn on the 'debug' filter, and look at the HTML that gets generated. It will leave some hints near your `<img>` tags indicating why optimizations may have failed.

**Comment by Pionell** [comment]
Thanks, they indicated that inline image filter failed.

**Comment by jmarantz** [comment]
The purpose of the 'debug' filter is that it provides more detail about why optimizations failed, so it can be diagnosed and, if possible, corrected.

**Comment by Pionell** [comment]
For now i disabled the inline image filter, however the issue with the images not being optimised for pagespeed is still there, what can I do debugging wise?

**Comment by jmarantz** [comment]
Can you paste the rewritten HTML for the img tags that failed to optimize, with the debug filter enabled?

**Comment by Pionell** [comment]
I have an interesting bug where some of the images do not load, but if i add the "?PageSpeedFilters=+debug" the images do load how they are supposed to. 

one of the failed images: 
```
<img class="lazy error" data-src="/image/1496677975_21135-f--daria,284review,29.png.pagespeed.ce.ReU17Ivulo.jpg" alt=" alt info" itemprop="image" width="283" height="358" src="/image/1496677975_21135-f--daria,284review,29.png.pagespeed.ce.ReU17Ivulo.jpg" data-was-processed="true">
```


Filters:

```
ModPagespeedDisableFilters lazyload_images,inline_javascript,rewrite_images,convert_jpeg_to_webp,convert_to_webp_lossless,convert_to_webp_animated,recompress_webp,convert_jpeg_to_webp
ModPagespeedEnableFilters extend_cache
ModPagespeedDisableFilters convert_png_to_jpeg
 ModPagespeedEnableFilters defer_javascript
ModPagespeedDisableFilters inline_images
```

**Comment by oschaaf** [comment]
@Pionell that sounds like a bug that was solved at some point. Which mod_pagespeed version are you running?

**Comment by Pionell** [comment]
x-mod-pagespeed: 1.13.35.2-0

**Comment by Pionell** [comment]
i noticed that if i disable and forbid the inline_images filter the images are still failing, however if i also disable : 
```
  ModPagespeedDisableFilters inline_images,rewrite_images,resize_rendered_image_dimensions,recompress_images
  ModPagespeedForbidFilters inline_images,rewrite_images,resize_rendered_image_dimensions,recompress_images
```
filters the images start to load normally. Is the inline image filter incorporated into rewrite_images/resize_images filters and overwriting the disable? Or is the .ic in the name of the file not inline images? Is this a known issue to you guys or is this only happening to me? maybe there is a misconfiguration in the varnish + pagespeed? i'm a little bit lost here..

**Comment by jmarantz** [comment]
Hi -- quick question and a couple of comments.

Do you have another lazy-loader apart from mod_pagespeed running on your site? If so, could you try temporarily disabling your other lazy-loader and instead using 

`    ModPagespeedEnableFilters`  [lazyload_images](https://www.modpagespeed.com/doc/filter-lazyload-images)

I'm not saying mod_pagespeed's lazyloader is necessarily better than the other one you have, but I think mod_pagespeed's URL-renaming may not work well with the other lazy-loader.

One other thing that can be confusing when bringing up mod_pagespeed for the first time is that its optimizations don't occur instantly. They are initiated the first time a web-page is seen, and are cached server-side asynchronously, when they complete. In order to see the fully optimized view you may have to visit the page and refresh a few times to warm up the server-side cache.

This is confusing for two reasons:
  - if something is broken due to changed URLs interacting with JS on your page (e.g. another lazyload library) it may look like it works initially, and then fails later once the optimization is cached
  - if you are looking for optimized results you may not see them immediately and think you did something wrong, when that's the way it's supposed to work.

By the way, the addition of Varnish downstream can also confuse things, but once you get everything configured properly it's a great combination. Please read https://www.modpagespeed.com/doc/downstream-caching for more details.

In general, in the release you have, we believe the image optimization in all its forms should be working properly. So all of the disables and forbids you indicated above should not be necessary.

Finally, if all you want to do is make your images smaller, you might want to consider mod_pagespeed's OptimizeForBandwith mode.  See https://www.modpagespeed.com/doc/optimize-for-bandwidth for details.

**Comment by Pionell** [comment]
Hey,
I've checked out a couple of my websites that don't have lazyload - they have the same issues described above. I'm thinking this is varnish after all, I will investigate and will get back to you.
